import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 400, height: 300 } });
page.on('console', (m) => console.log('[c]', m.text()));
page.on('pageerror', (e) => console.log('[err]', e.message));
await page.goto('file:///home/user/claude/dist/sakura-michi.html?q=high&noloop');
await page.waitForFunction(() => window.__ready === true, null, { timeout: 120000 });
const r = await page.evaluate(process.argv[2]);
console.log(JSON.stringify(r, null, 1));
await browser.close();
